--- 
title: "Maxfield Meadow Ipomopsis Volatiles"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
.main-container { max-width: 1000px; margin-left: 0; margin-right: auto; }
img{ max-width:200%; height: auto; }
td, th { padding : 6px }
</style>


```{r setup, message=FALSE}
library(tidyverse)
library(lubridate)
#library(googlesheets4)
library(vegan)
library(viridis)
library(ggvegan)

library(knitr)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, fig.path = "images_volatiles/")
options(digits=4) # for kables

load("data/maxfield_data.rda")
```

# Sample size

```{r sampsize}
with(vt, table(year, type)) %>% kable
with(vt %>% filter(type=="floral"), table(year, water, snow))
```

# Soil moisture

```{r sm, fig.height=7, fig.width=6}
ggplot(vt %>% drop_na(water), aes(x=factor(date), y=VWC, color=water)) + facet_wrap(vars(year), ncol = 1, scales="free_x") +
  geom_boxplot() + scale_color_manual(values=water_pal) + scale_x_discrete(guide = guide_axis(angle=90)) + 
  labs(x="Date", y="Soil moisture (%VWC)", color="Precipitation")
```

