--- 
title: "Maxfield Meadow Ipomopsis Volatiles"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
.main-container { max-width: 1000px; margin-left: 0; margin-right: auto; }
img{ max-width:200%; height: auto; }
td, th { padding : 6px }
</style>


```{r setup, message=FALSE}
library(tidyverse)
library(lubridate)
library(vegan)
library(viridis)
library(ggvegan)

library(knitr)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, fig.path = "images_volatiles2020/", fig.height=8, fig.width=8)
options(digits=4) # for kables

load("data/maxfield_data.rda")
load("data/volatiles/maxfield_volatiles.rda")
```

# Sample size

```{r sampsize}
with(vt, table(year, type)) %>% kable
with(vt %>% filter(type=="floral"), table(year, water, snow))
```

# Soil moisture

```{r sm}
ggplot(vt %>% drop_na(water), aes(x=factor(date), y=VWC, color=water)) + facet_wrap(vars(year), ncol = 1, scales="free_x") +
  geom_boxplot() + scale_color_manual(values=water_pal) + scale_x_discrete(guide = guide_axis(angle=90)) + 
  labs(x="Date", y="Soil moisture (%VWC)", color="Precipitation")
```

# Multivariate analyses

```{r samplesizes}
volsmeta <- maxfmeta %>% mutate(year=factor(year(sampledate))) %>% 
  drop_na(plotid) %>% #cut out ambients
  filter(year %in% c("2018","2019","2020")) %>% droplevels() %>% left_join(treatments)
rownames(volsmeta) <- volsmeta$index
vols <- maxf[volsmeta$index,]

with(maxfmeta, table(type))
with(volsmeta, table(year, plotid))
with(volsmeta, table(water, snow, year))

volsmeta %>% drop_na(sampledate) %>% group_by(sampledate) %>% tally() %>% 
  ggplot(aes(x=yday(sampledate), y=n)) + geom_col() + facet_wrap(vars(year(sampledate)), ncol=1) +
  labs(x="VOC sampling date (day of year)", y="Floral samples")
# TODO fix early 2020 date? and check singletons in 2018, 2019
# TODO there are some duplicate file names in maxfmeta, especially sampled 190805
```

```{r filtering}
vols.cut <- vols[,colSums(vols)>1e7]

ipochems <- read_csv("data/volatiles/chemsf_ipo.csv")
ipogood <- ipochems %>% filter(verdict %in% c("bis14", "fvoc", "keep","keep_leaf","merge")) %>% pull(name)
vols.good <- vols[,intersect(colnames(vols),ipogood)]
```


## Heatmap

```{r heatmap}
library(viridis)
library(pheatmap)
log10(sum(vols.cut$`(1R)-2,6,6-Trimethylbicyclo[3.1.1]hept-2-ene`))
pheatmap(as.matrix(t(vols[,colSums(vols)>3e8]))^(1/4), color=mako(512),
         annotation_col=volsmeta %>% select(year))

pheatmap(as.matrix(t(vols.good))^(1/4), color=mako(512),
         annotation_col=volsmeta %>% select(year))
```

## Boxplots

```{r boxplots, fig.width=10, fig.height=10}
vols.good.top <- vols.good[,colSums(decostand(vols.good,"pa"))>81]#occur in more than N samples
bind_cols(volsmeta, vols.good.top) %>%  pivot_longer(-all_of(colnames(volsmeta))) %>% 
  ggplot(aes(x = year, fill = water, y = value)) + geom_boxplot() + facet_wrap(vars(name), scales="free_y") + 
  scale_y_sqrt() + scale_fill_manual(values=water_pal) + labs(x="Year", y ="Emissions (ng/hr)") + guides(color="none")
```

## Ordinations

### Absolute amounts

```{r hmb_ords}
#Nmds 
(scents.mds <- metaMDS(sqrt(scents.dat), autotransform=FALSE)) #had noshare = FALSE
plot(scents.mds,type="t",display=c("species"))
plot(scents.mds,type="t",display=c("sites"))

#PerMANOVA using adonis function in vegan package
(scents.permanova <- adonis(sqrt(scents.dat) ~ water * year, planttype.dat))

#Canonical analysis of principal coordinates (CAP) allows for other distance measures
(scents.cap <-capscale(sqrt(scents.dat) ~ year * water, planttype.dat, dist="bray"))
anova(scents.cap, by="term")

scents.cap <-capscale(sqrt(scents.dat) ~ year + water, planttype.dat, dist="bray")
plot(scents.cap, type="n", xlim=c(-2,2))
points(scents.cap, display = "sites", col=water_pal[planttype.dat$water], pch=as.integer(planttype.dat$year))
text(scents.cap, display="cn", labels=c("2018","2019", names(water_pal)), col=c("black","black",water_pal), font=2)

plot(scents.cap, type="n", xlim=c(-1,3), ylim=c(-0.5,0.5))
text(scents.cap, display="sp", cex=0.7)
```


### Relative amounts

```{r hmb_ords_rel}
#Nmds 
(scents.mds <- metaMDS(decostand(scents.dat, "hellinger"), autotransform=FALSE)) #had noshare = FALSE
plot(scents.mds,type="t",display=c("species"))
plot(scents.mds,type="t",display=c("sites"))

#PerMANOVA using adonis function in vegan package
(scents.permanova <- adonis(decostand(scents.dat, "hellinger") ~ water * year, planttype.dat))

#Canonical analysis of principal coordinates (CAP) allows for other distance measures
(scents.cap <-capscale(sqrt(scents.dat) ~ year * water, planttype.dat, dist="bray"))
anova(scents.cap, by="term")

scents.cap <-capscale(decostand(scents.dat, "hellinger") ~ year + water, planttype.dat, dist="bray")
plot(scents.cap, type="n", xlim=c(-2,2))
points(scents.cap, display = "sites", col=water_pal[planttype.dat$water], pch=as.integer(planttype.dat$year))
text(scents.cap, display="cn", labels=c("2018","2019", names(water_pal)), col=c("black","black",water_pal), font=2)

plot(scents.cap, type="n", xlim=c(-1.5,1.5), ylim=c(-0.5,0.5))
text(scents.cap, display="sp", cex=0.7)
```


