---
title: "Maxfield Meadow Ipomopsis Selection"
author: "[John Powers](http://sites.uci.edu/powers/)"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: no
    lib_dir: libs
    code_folding: hide
    toc: yes
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---


```{r setup, message=FALSE}
library(tidyverse)
library(knitr)
library(emmeans)
library(broom)
library(lme4)
library(lmerTest)
knitr::opts_chunk$set(comment="", cache=T, warning = F, message = F, 
                      fig.path = "images_selection/", dev="svglite", dev.args=list(fix_text_size=FALSE), fig.height=6, fig.width=6)
options(digits=3) # for kables

load("data/maxfield_data.rda") #load trait measurements, etc
mnps.plantyr <- mnps.plantyr %>% mutate(prop_uninfested = 1 - prop_infested)

fitnesstraits <- c("seeds_est", "seeds_per_flower", "prop_uninfested", "eggs_per_flower")
fitnessnames <- c(traitnames, prop_uninfested = "Prop. uneaten fruits",
                  eggs_per_flower="Fly eggs per flower")[fitnesstraits]
morphtraits <- c("corolla_length", "corolla_width","style_length","anther_max","anther_min","sepal_width","nectar_24_h_ul", "nectar_conc")
```

# Fitness vs. environment

## Fitness vs. VWC

```{r fitness_sm, fig.height=4, fig.width=4}
#See if VWC affects relative fitness
ggplot(mnps.plantyr, aes(x=VWC, y=seeds_est, color=year)) + geom_point() + geom_smooth(method="lm",se=F) + 
  labs(x="VWC", y="Seed production", color="year")+ theme_bw() + scale_color_manual(values=year_pal)

seeds.mod.sm <- lmer(seeds_rel ~ VWC * year + (1|plotid), 
                     data=mnps.plantyr %>% group_by(year) %>% mutate(seeds_rel = seeds_est/mean(seeds_est, na.rm=T)))
anova(seeds.mod.sm, ddf="Ken") %>% kable()
emtrends(seeds.mod.sm, ~year, var="VWC") %>% kable()
```

# Selection on individual traits

```{r mt_selection, fig.height=8, fig.width=6}
walk(fitnesstraits, ~ 
       print(mnps.plantyr %>% 
               mutate(prop_uninfested = if_else(fruits_nonaborted > 4, prop_uninfested, NA)) %>% 
               pivot_longer(all_of(floraltraits)) %>% 
               ggplot(aes_string(y=.x, x="value", color="year")) + 
               geom_point() + geom_smooth(method="lm", se=F) + 
               facet_wrap(vars(name), scales="free_x", labeller=as_labeller(traitnames)) + 
               labs(y=fitnessnames[.x], color="Year")+
               theme_bw() + scale_color_manual(values=year_pal) + theme(axis.title.x=element_blank()))) 
```

```{r mt_indiv_mod}
#TODO split up by year
mt.mod.indiv <- expand_grid(trait=floraltraits, fitnesstrait=fitnesstraits) %>% 
  mutate(model = pmap(., function(trait, fitnesstrait) {
    lm(relfitness ~ trait.z * year, 
       data=mnps.plantyr %>% mutate(trait.z = mnps.plantyr[[trait]] / alltraits.sd[[trait]]) %>% 
         rename("fitness" = fitnesstrait) %>% 
         group_by(year) %>% mutate(relfitness = fitness/mean(fitness, na.rm=T)))}), # mean fitness in each yr
    coef = map(model, tidy),
    test = map(model, ~tidy(car::Anova(.x), type=3)),
    emm = map(model, ~summary(emtrends(.x, ~1, var="trait.z")))) 

#get the the standardized selection differential S' (change in relative fitness / standardized trait value)
mt.mod.indiv %>% select(trait, fitnesstrait, coef) %>% unnest(coef) %>% filter(term=="trait.z") %>% 
  ggplot(aes(x=traitnames[trait], y=estimate, ymin=estimate-std.error, ymax=estimate+std.error)) + 
  facet_wrap(vars(fitnesstrait), labeller = as_labeller(fitnessnames)) + 
  geom_hline(yintercept=0) + geom_pointrange() + coord_flip() + 
  labs(y="Standardized selection differential S'") + theme(axis.title.y=element_blank())
```

# Selection gradients from PCA

Following method of [Chong et al. 2018](https://doi.org/10.1002/evl3.63) for reconstructing selection estimates from estimates of selection on PCs: Beta = E * A.

* PCA can't handle missing values so they are removed, but this biases the data and reduces sample size - multiple imputation?

```{r gradients, fig.width=4, fig.height=3}
calculate_beta <- function(E, slopes) {
  data.frame(B = E %*% slopes$A,
             SE = sqrt(E ^ 2 %*% slopes$SE ^ 2)) %>% 
    mutate(p.value = pt(abs(B)/SE, df=1, lower.tail=F)) %>% #calculate t statistic from difference in means and SE, then look up one-tailed p with 1 df in the upper tail
    rownames_to_column("trait")
}
plot_beta <- function(beta) {
  beta %>% mutate(trait = fct_reorder(trait, B)) %>% 
    ggplot(aes(y=trait, x = B, xmin=B-SE, xmax=B+SE)) + 
    geom_vline(xintercept=0)+ geom_pointrange() + 
    labs(x = "Selection gradient (beta) estimated from gradients on PCs", y = "Trait")
}

mnps.plantyr.std <- mnps.plantyr %>% select(all_of(morphtraits),seeds_est, any_of(names(treatments))) %>% 
  mutate(across(all_of(morphtraits), ~ (.x-mean(.x, na.rm=T))/sd(.x, na.rm=T))) %>% 
  group_by(year) %>% mutate(seeds_rel = seeds_est/mean(seeds_est, na.rm=T), .keep="unused") %>% ungroup %>% 
  drop_na(all_of(morphtraits)) 

# Run PCA on traits
mnps.PCA <- mnps.plantyr.std %>% select(all_of(morphtraits)) %>% prcomp() 
summary(mnps.PCA) # PCs 1 - 5 explain 90% of the variation
mnps.PCA.E <- mnps.PCA$rotation[,1:5]
mnps.plantyr.std.PCA <- bind_cols(mnps.plantyr.std, as.data.frame(mnps.PCA$x))

# Regress relative fitness on PCs
mnps.PCA.regression <- lm(seeds_rel ~ PC1 + PC2 + PC3 + PC4 + PC5, data = mnps.plantyr.std.PCA)
mnps.PCA.slopes <- tidy(mnps.PCA.regression) %>% filter(term != "(Intercept)") %>% rename(A=estimate, SE=std.error)

# Convert selection gradients on PCs to gradients on traits
(mnps.beta <- calculate_beta(mnps.PCA.E, mnps.PCA.slopes)) %>% kable(caption="selection gradients estimated from PCs")
plot_beta(mnps.beta)
```

